name: Auto Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Generate release info
        id: info
        run: |
          $date = Get-Date -Format "yyyy.MM.dd.HHmm"
          $short_sha = "${{ github.sha }}".Substring(0,7)
          $version = "build-$date-$short_sha"
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "date=$date" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.info.outputs.version }}
          name: "Blackjack2 ${{ steps.info.outputs.version }}"
          body: |
            Automated build from latest commit

            Build date: ${{ steps.info.outputs.date }}
            Commit: ${{ github.sha }}

            Download blackjack2.exe and run directly - no installation needed!
          files: target/release/blackjack2.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
